AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String
  BranchName:
    Type: String
  ArtifactBucketArn:
    Type: String
  CommitHash:
    Type: String
  DockerRepo:
    Type: String


Resources:
  ServiceCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-${BranchName}-CodeBuildProject-Service
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        EnvironmentVariables:
          - Name: BucketName
            Value: !ImportValue CodeBucketName
          - Name: ProjectName
            Value: !Ref ProjectName
          - Name: CommitHash
            Value: !Ref CommitHash
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Value: !Ref DockerRepo
          - Name: IMAGE_TAG
            Value: !Ref CommitHash
          - Name: PY_PI_URL
            Value: !ImportValue T3chFlicksUsersPyPiURL
      Source:
        Type: CODEPIPELINE
        BuildSpec: aws/service-buildspec.yml
      TimeoutInMinutes: 10


  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: ArtifactBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - "s3:*"
                Effect: Allow
                Resource: 
                  - !Sub ${ArtifactBucketArn}/*
                  - !Sub ${ArtifactBucketArn}
        - PolicyName: CodeBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - "s3:*"
                Effect: Allow
                Resource: 
                  - !Sub 
                    - ${BucketArn}/*
                    - BucketArn: !ImportValue CodeBucketArn
                  - !ImportValue CodeBucketArn
        - PolicyName: LogsCreation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:CreateLogStream'
                - 'logs:CreateLogGroup'
                - 'logs:PutLogEvents'
                Effect: Allow
                Resource: "*"                 
        - PolicyName: "DecryptSecrets"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:DescribeParameters
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - kms:Decrypt
                Resource: 
                  - !ImportValue KMSKeyArn
                  - !Sub arn:aws:ssm:eu-west-1:${ AWS::AccountId }:parameter/DOCKER_PASS          
        - PolicyName: ecrBuild
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'ecr:GetAuthorizationToken'
                - 'ecr:BatchCheckLayerAvailability'
                - 'ecr:CompleteLayerUpload'
                - 'ecr:InitiateLayerUpload'
                - 'ecr:PutImage'
                - 'ecr:UploadLayerPart'
                Effect: Allow
                Resource: 
                  - "*"